        
        
kind: Deployment
apiVersion: apps/v1
metadata:
  name: studentmanagment
  namespace: demo
  labels:
    app: studentmanagment
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentmanagment
      version: v1
  template:
    metadata:
      labels:
        app: studentmanagment
        version: v1
    spec:
      containers:
        - name: studentmanagment
          image: 737971166371.dkr.ecr.us-east-1.amazonaws.com/studentmanagment:${IMAGE_TAG}
          ports:
            - name: application
              containerPort: 8080
