apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: studentmanagment
    app.kubernetes.io/instance: studentmanagment
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: studentmanagment
  name: studentmanagment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentmanagment
  template:
    metadata:
      labels:
        app: studentmanagment
    spec:
      containers:
        - image: 737971166371.dkr.ecr.us-east-1.amazonaws.com/studentmanagment:${IMAGE_TAG}
          imagePullPolicy: Always
          name: studentmanagment
          ports:
            - containerPort: 8080
