

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: students
  namespace: demo
  labels:
    app: students

spec:  
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: studentmanagment
            port:
              number: 8080
