

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studentmanagment
  namespace: demo
  labels:
    app: studentmanagment
    service: studentmanagment
spec:  
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: studentmanagment
            port:
              number: 8080
