apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: studentmanagment
    app.kubernetes.io/instance: studentmanagment-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: studentmanagment
  name: studentmanagment
  namespace: demo
spec:
  selector:
    app: studentmanagment
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
